# doing network configuration on all instances
- name: Set network proxy to connect to outside world
  become: true
  copy:
    src: ./files/network-proxy/environment
    dest: /etc/environment

### install dependency for docker and docker
#- name: Install dependency for docker
#  raw:  sudo apt-get -y install \
#    apt-transport-https \
#    ca-certificates \
#    curl \
#    gnupg-agent \
#    software-properties-common





# install docker
- name: Copy install docker shell
  become: true
  copy:
    src: ./files/install-docker/docker_install.sh
    dest: /home/ubuntu/docker_install.sh
    mode: 0755

- name: Install docker
  raw: sudo ./docker_install.sh

# create directory to set docker proxy
- name: Create docker directory
  become: true
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory


- name: Setup docker demon proxy
  become: true
  copy:
    src: ./files/docker-proxy/http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf


- name: Flush docker changes
  raw: sudo systemctl daemon-reload

- name: Restart docker
  raw: sudo systemctl restart docker


# add sudo permission to user that enable user do not have to use sudo
- name: Create the docker group
  raw: |
    if grep -q docker /etc/group
    then
          echo "group exists"
    else
          echo "group does not exists"
          sudo groupadd docker.
    fi

- name: Add your user to the docker
  raw: sudo usermod -aG docker $USER

- name: Restart docker
  raw: sudo systemctl restart docker

- name: Docker socket
  raw: sudo chmod a+rw /var/run/docker.sock



- name: Install Python
  raw: sudo apt-get -y install  python3-pip vim python3
